Fix: Cannot assign to constant 'uploadData'
The error TS2588 in `ClearQRPDFEditor.tsx` was caused by attempting to assign a value to a constant variable `uploadData`. This commit resolves the error by changing the declaration of `uploadData` to `let` so that it can be reassigned.